# Generated by Django 5.2 on 2025-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_vendor_data_rules_remove_vendor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='parser',
            field=models.CharField(blank=True, help_text='Parser method to use for extracting invoice data', max_length=255, null=True),
        ),
    ]
