# Generated by Django 5.2 on 2025-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_vendor_data_rules_alter_processedemail_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarule',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='datarule',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='datarule',
            name='validation_regex',
        ),
        migrations.AlterField(
            model_name='datarule',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('email', 'Email'), ('phone', 'Phone'), ('line_items', 'Line Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datarule',
            name='table_config',
            field=models.JSONField(blank=True, default={'header_text': 'Description', 'item_columns': {'description': 1, 'id': 0, 'quantity': 2, 'unit_price': 3}, 'start_row_after_header': 1}, help_text="For table-based extraction: {'start_row_after_header': int, 'item_columns': key/value pairs, 'header_text': str}", null=True),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='invoice_type',
            field=models.CharField(choices=[('pdf', 'PDF')], max_length=255),
        ),
    ]
