# Generated by Django 5.2.10 on 2026-05-19 03:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_vendor_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_process_enabled', models.BooleanField(default=False)),
                ('max_email_age_days', models.PositiveIntegerField(default=30, help_text='Skip Gmail messages older than this many days.', validators=[django.core.validators.MinValueValidator(1)])),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60, help_text='How often the background worker checks for new invoices.', validators=[django.core.validators.MinValueValidator(10)])),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=255)),
                ('item_id', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('current_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_total_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_email_id', models.CharField(max_length=255, unique=True)),
                ('source_email_subject', models.CharField(blank=True, default='', max_length=512)),
                ('source_email_from', models.CharField(blank=True, default='', max_length=512)),
                ('source_email_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_po', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='processedemail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='invoices.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='DataRule',
        ),
    ]
