# Generated by Django 5.2.10 on 2026-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_itemtype_contact_invoice_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice email was received or ingested.', null=True),
        ),
    ]
