# Generated by Django 5.2.10 on 2026-05-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_itemtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
