# Generated by Django 5.2.10 on 2026-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_remove_vendor_spreadsheet_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
