# Generated by Django 5.2.10 on 2026-05-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_vendor_ignore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.itemtype'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_itemtype_parent_name'),
        ),
    ]
